version: '3.8'

services:
  # Service cho Backend Flask
  backend:
    build: ./backend
    restart: always
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  # Service cho Frontend React
  frontend:
    build: ./frontend
    restart: always

  # Service cho Nginx Reverse Proxy
  nginx-proxy:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      # THÊM DÒNG NÀY: Mở port 443 cho HTTPS/SSL
      - "443:443"
    volumes:
      # THÊM CỜ :z ở cuối để cho phép SELinux truy cập
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # THÊM CỜ :z ở cuối để cho phép SELinux truy cập
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend